# Generated by Django 4.2.1 on 2023-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='discription',
            field=models.TextField(default='', max_length=100),
        ),
    ]
