# Generated by Django 4.2.1 on 2023-06-02 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
