# Generated by Django 4.2.1 on 2023-06-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
